// First-time owner guides (English)
import type { FirstTimeGuide } from "./wikiGuideData";

export const CAT_FIRST_TIME_GUIDE_EN: FirstTimeGuide = {
  species: "cat",
  monthlyMinCost: "₩80,000",
  monthlyMaxCost: "₩200,000",
  steps: [
    {
      order: 1,
      title: "Initial Health Check",
      description: "Visit a vet for a baseline health check first. Includes FeLV/FIV tests, deworming, and basic blood work.",
      timing: "Within 1–3 days of adoption",
      estimatedCost: "₩50,000–150,000",
      icon: "🏥",
    },
    {
      order: 2,
      title: "Pet Registration",
      description: "Insert an internal microchip and complete national pet registration. Dramatically improves recovery odds if lost.",
      timing: "Within 30 days of adoption",
      estimatedCost: "₩10,000–30,000",
      icon: "📋",
    },
    {
      order: 3,
      title: "Start Vaccinations",
      description: "Consult your vet for a schedule. Core vaccines: panleukopenia, calicivirus, herpesvirus (FVRCP) + rabies.",
      timing: "From 6–8 weeks old",
      estimatedCost: "₩30,000–50,000 per dose",
      icon: "💉",
    },
    {
      order: 4,
      title: "Spay or Neuter",
      description: "Major health benefits: reduced heat-cycle stress, lower risk of pyometra and mammary tumors.",
      timing: "Around 5–6 months old",
      estimatedCost: "₩150,000–300,000",
      icon: "✂️",
    },
    {
      order: 5,
      title: "Indoor Setup",
      description: "Provide litter boxes (number of cats + 1), vertical space (cat tree), scratchers, and hideouts.",
      timing: "Before or right after adoption",
      estimatedCost: "₩100,000–300,000",
      icon: "🏠",
    },
    {
      order: 6,
      title: "Food & Water Routine",
      description: "Choose age- and health-appropriate food, establish measured feeding, use a water fountain to encourage hydration.",
      timing: "Right after adoption",
      estimatedCost: "₩30,000–80,000/mo",
      icon: "🍽️",
    },
  ],
  essentialSupplies: [
    { item: "Litter box + litter", estimatedCost: "₩30,000–100,000", priority: "필수" },
    { item: "Food + treats", estimatedCost: "₩30,000–80,000/mo", priority: "필수" },
    { item: "Water fountain", estimatedCost: "₩20,000–50,000", priority: "필수" },
    { item: "Cat tree", estimatedCost: "₩30,000–150,000", priority: "필수" },
    { item: "Scratcher", estimatedCost: "₩10,000–30,000", priority: "필수" },
    { item: "Carrier", estimatedCost: "₩20,000–50,000", priority: "필수" },
    { item: "Toys (wand, etc.)", estimatedCost: "₩10,000–30,000", priority: "권장" },
    { item: "Grooming brush", estimatedCost: "₩10,000–20,000", priority: "권장" },
  ],
  vaccinationSchedule: [
    { age: "6–8 weeks", vaccine: "1st FVRCP vaccine", cost: "₩30,000–50,000" },
    { age: "10–12 weeks", vaccine: "2nd FVRCP vaccine", cost: "₩30,000–50,000" },
    { age: "14–16 weeks", vaccine: "3rd FVRCP + rabies", cost: "₩50,000–80,000" },
    { age: "1 year later", vaccine: "Booster (FVRCP + rabies)", cost: "₩50,000–80,000" },
    { age: "Annually", vaccine: "Annual booster", cost: "₩50,000–80,000" },
  ],
};

export const DOG_FIRST_TIME_GUIDE_EN: FirstTimeGuide = {
  species: "dog",
  monthlyMinCost: "₩100,000",
  monthlyMaxCost: "₩300,000",
  steps: [
    {
      order: 1,
      title: "Initial Health Check",
      description: "Visit a vet first. Includes patellar luxation grade, deworming, and basic blood tests.",
      timing: "Within 1–3 days of adoption",
      estimatedCost: "₩50,000–150,000",
      icon: "🏥",
    },
    {
      order: 2,
      title: "Pet Registration (Mandatory)",
      description: "Internal microchip + national registration. Failure to register is subject to fines in Korea.",
      timing: "Within 30 days of adoption",
      estimatedCost: "₩10,000–30,000",
      icon: "📋",
    },
    {
      order: 3,
      title: "Start Vaccinations",
      description: "DHPPL 5-way + corona + kennel cough + rabies. Consult your vet for the schedule.",
      timing: "From 6–8 weeks old",
      estimatedCost: "₩30,000–50,000 per dose",
      icon: "💉",
    },
    {
      order: 4,
      title: "Heartworm Prevention",
      description: "Potentially fatal mosquito-borne disease. Monthly preventive medication is essential.",
      timing: "Monthly from 8 weeks old",
      estimatedCost: "₩10,000–30,000/mo",
      icon: "🛡️",
    },
    {
      order: 5,
      title: "Spay or Neuter",
      description: "Prevents prostate disease and pyometra. Also helps with behavioral issues.",
      timing: "5–8 months old",
      estimatedCost: "₩200,000–400,000",
      icon: "✂️",
    },
    {
      order: 6,
      title: "Start Basic Training",
      description: "Sit, stay, come + potty training. Critical socialization window: 3–12 weeks old.",
      timing: "Right after adoption",
      estimatedCost: "Free (self) / ₩200,000–500,000/mo (trainer)",
      icon: "🎓",
    },
  ],
  essentialSupplies: [
    { item: "Food + treats", estimatedCost: "₩50,000–150,000/mo", priority: "필수" },
    { item: "Food/water bowls", estimatedCost: "₩10,000–30,000", priority: "필수" },
    { item: "Harness + leash", estimatedCost: "₩20,000–50,000", priority: "필수" },
    { item: "Pee pads (indoor)", estimatedCost: "₩10,000–30,000/mo", priority: "필수" },
    { item: "Crate/bed", estimatedCost: "₩30,000–100,000", priority: "필수" },
    { item: "Toys", estimatedCost: "₩10,000–30,000", priority: "필수" },
    { item: "Grooming supplies", estimatedCost: "₩20,000–50,000", priority: "권장" },
    { item: "Dental care items", estimatedCost: "₩10,000–20,000", priority: "권장" },
  ],
  vaccinationSchedule: [
    { age: "6–8 weeks", vaccine: "1st DHPPL + Corona", cost: "₩30,000–50,000" },
    { age: "10–12 weeks", vaccine: "2nd DHPPL + Corona", cost: "₩30,000–50,000" },
    { age: "14–16 weeks", vaccine: "3rd DHPPL + Kennel Cough", cost: "₩40,000–60,000" },
    { age: "16+ weeks", vaccine: "DHPPL + rabies", cost: "₩50,000–80,000" },
    { age: "Annually", vaccine: "Annual booster", cost: "₩50,000–80,000" },
  ],
};
