"use client";
import { useState, useEffect } from "react";
import { useAppStore } from "../lib/store";
import { supabase } from "../lib/supabase";
import { isAutoGeneratedNickname } from "../lib/utils";

// 자동 생성 닉네임을 가진 사용자가 로그인 중이면 강제로 닉네임 설정 모달 표시.
// 사용자가 회원가입/소셜로그인 시 닉네임을 정하지 않은 경우 임시 자동 닉네임을
// 직접 고른 이름으로 바꾸도록 유도.
export default function NicknameSetupModal() {
  const user = useAppStore((s) => s.user);
  const setUser = useAppStore((s) => s.setUser);
  const [open, setOpen] = useState(false);
  const [newNick, setNewNick] = useState("");
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState("");

  useEffect(() => {
    if (!user || user.id === "demo-user") { setOpen(false); return; }
    if (isAutoGeneratedNickname(user.nickname)) {
      // localStorage로 "오늘 미루기" 처리 (계속 강요하지 않음, 단 24시간 후 다시 표시)
      const snoozeUntil = Number(localStorage.getItem("nick_setup_snooze") || 0);
      if (Date.now() < snoozeUntil) return;
      setOpen(true);
    } else {
      setOpen(false);
    }
  }, [user]);

  const save = async () => {
    if (!user) return;
    const n = newNick.trim();
    if (n.length < 2 || n.length > 12) { setMsg("2~12자로 입력해주세요."); return; }
    if (n.includes("@")) { setMsg("이메일은 닉네임으로 쓸 수 없어요."); return; }
    if (isAutoGeneratedNickname(n)) { setMsg("자동 생성된 형식과 비슷합니다. 다른 이름으로 정해주세요."); return; }

    setSaving(true);
    setMsg("");

    // 중복 확인
    const { data: dup } = await supabase
      .from("users")
      .select("id")
      .eq("nickname", n)
      .neq("id", user.id)
      .maybeSingle();
    if (dup) { setSaving(false); setMsg("이미 사용 중인 닉네임입니다."); return; }

    const { error } = await supabase
      .from("users")
      .update({ nickname: n, nickname_set_by_user: true })
      .eq("id", user.id);
    setSaving(false);
    if (error) { setMsg("변경 실패: " + error.message); return; }

    setUser({ ...user, nickname: n });
    setOpen(false);
  };

  const snooze = () => {
    // 24시간 미루기
    localStorage.setItem("nick_setup_snooze", String(Date.now() + 24 * 60 * 60 * 1000));
    setOpen(false);
  };

  if (!open) return null;

  return (
    <div
      style={{
        position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)",
        display: "flex", alignItems: "center", justifyContent: "center",
        zIndex: 10000, padding: 16,
      }}
    >
      <div
        style={{
          background: "#fff", borderRadius: 14, padding: 24,
          maxWidth: 380, width: "100%", boxShadow: "0 12px 40px rgba(0,0,0,0.25)",
        }}
      >
        <div style={{ fontSize: 32, marginBottom: 8, textAlign: "center" }}>👋</div>
        <h2 style={{ margin: "0 0 6px", fontSize: 18, fontWeight: 800, textAlign: "center", color: "#1D1D1F" }}>
          닉네임을 직접 정해주세요
        </h2>
        <p style={{ margin: "0 0 16px", fontSize: 13, color: "#6B7280", textAlign: "center", lineHeight: 1.6 }}>
          현재 임시 닉네임 <b style={{ color: "#FF6B35" }}>{user?.nickname}</b>이 표시되고 있어요.
          <br />피드·댓글에 노출될 이름을 선택해주세요.
        </p>

        <input
          type="text"
          value={newNick}
          onChange={(e) => setNewNick(e.target.value)}
          placeholder="예: 멍멍이엄마, 고양이대디"
          maxLength={12}
          style={{
            width: "100%", padding: "12px 14px", border: "1.5px solid #E5E7EB",
            borderRadius: 10, fontSize: 14, outline: "none", fontFamily: "inherit",
            marginBottom: 8, boxSizing: "border-box",
          }}
        />
        {msg && (
          <div style={{ fontSize: 12, color: "#EF4444", marginBottom: 8 }}>{msg}</div>
        )}
        <p style={{ margin: "0 0 16px", fontSize: 11, color: "#9CA3AF" }}>
          2~12자 · 이미 사용 중인 닉네임은 불가
        </p>

        <button
          onClick={save}
          disabled={saving}
          style={{
            width: "100%", padding: "12px", background: saving ? "#9CA3AF" : "#FF6B35",
            color: "#fff", border: "none", borderRadius: 10, fontWeight: 700,
            fontSize: 14, cursor: saving ? "default" : "pointer", fontFamily: "inherit",
            marginBottom: 8,
          }}
        >
          {saving ? "저장 중..." : "이 닉네임으로 정할래요"}
        </button>
        <button
          onClick={snooze}
          style={{
            width: "100%", padding: "10px", background: "transparent",
            color: "#9CA3AF", border: "none", fontSize: 12,
            cursor: "pointer", fontFamily: "inherit",
          }}
        >
          나중에 (마이페이지에서 설정 가능)
        </button>
      </div>
    </div>
  );
}
